### ISSUE TITLE
Apple Podcasts fullscreen issue

### ISSUE THREAD

**Issue by konopielko** [trevorsharp/twitchpod#6]
There is some kind of issue between twitchpod videos and apple podcasts - It comes down to the ability to fullscreen the video only once per play. If I want to make it fullscreen again I need to play a different the video or force restart the podcasts app. I stumble upon it a lot because I usually play videos in pip mode and if there is something I want to focus on in the video I fullscreen it and then later I turn the pip mode again. This issue happens only with the videos from twitchpod and not with youtubecast so I think it might be because of the twitchpod video format.
I tested it on different video qualities, on macOS 13.0 and iOS 16.1

**Comment by trevorsharp** [comment]
This is a bug with Apple Podcasts. It only seems to happen with HLS video. They play without issue, but they run into issues with entering fullscreen. And since Twitch is serving their video as HLS playlists, I haven't been able to find any workaround that would work outside of downloading all the videos to a server and transcoding to a different container, which reduces a lot of the value of this project.

I filed a bug report (FB9937692) with Apple back in March 2022, but I doubt this issue will get resolved anytime soon (if ever). I ended up switching to Pocket Casts for my personal use because of this bug, and it's been able to handle the HLS video without many issues (downloads don't work and it doesn't play nice on the web version of Pocket Casts in Chrome).

**Comment by trevorsharp** [comment]
As of iOS 17 betas, it seems that HLS video is no longer supported at all in Apple Podcasts for iOS, which is a shame. I’ve updated the twitchPOD UI to display this limitation and encourage use of Pocket Casts or using an audio only feed as the only known alternatives.
